import Mathlib

/-!
# Lattices in quadratic spaces

Basic definitions following O'Meara, *Introduction to Quadratic Forms*, §81–82.

## Conventions

* `K` is a field and `R` a subring with `Algebra R K`. The intended cases are
  `R = 𝓞 K` for a number field `K`, and `R = 𝓞_𝔭` for a completion `K_𝔭`.
  Most definitions only need `Algebra R K`; theorems add `[IsDedekindDomain R]`,
  `[IsFractionRing R K]` etc. as required.
* A *quadratic space* is a `K`-vector space `V` with a **symmetric bilinear form** `B`,
  and the quadratic form is `Q x = B x x` (O'Meara's convention, as in the PVYY paper).
  We work with `B` rather than Mathlib's `QuadraticForm`, whose conventions differ by
  a factor of 2 (`QuadraticMap.polar`).
* A *lattice in* `V` is a finitely generated `R`-submodule of `V`; it is a lattice
  *on* `V` if it spans `V` over `K`.
* Lattices are **not** assumed to be free: over `𝓞 K` with nontrivial class group
  they need not be. This is why lattices are `Submodule`s rather than Gram matrices.
-/

namespace LatticesLean

section Space

variable {K : Type*} [Field K] {V : Type*} [AddCommGroup V] [Module K V]

/-- The bilinear form `B` is symmetric. -/
def IsSymm (B : LinearMap.BilinForm K V) : Prop :=
  ∀ x y, B x y = B y x

/-- The bilinear form `B` is nondegenerate (O'Meara: the space is *regular*). -/
def IsNondegenerate (B : LinearMap.BilinForm K V) : Prop :=
  ∀ x, (∀ y, B x y = 0) → x = 0

end Space

section Lattice

variable {R : Type*} [CommRing R] {K : Type*} [Field K] [Algebra R K]
variable {V : Type*} [AddCommGroup V] [Module K V] [Module R V] [IsScalarTower R K V]

/-- A *lattice in* `V`: a finitely generated `R`-submodule of `V`. -/
def IsLattice (L : Submodule R V) : Prop :=
  L.FG

variable (K) in
/-- A lattice *on* `V`: a lattice in `V` that spans `V` over `K`. -/
def IsLatticeOn (L : Submodule R V) : Prop :=
  L.FG ∧ Submodule.span K (L : Set V) = ⊤

variable (K) in
/-- The rank of `L`, i.e. `dim_K (K L)`. -/
noncomputable def latticeRank (L : Submodule R V) : ℕ :=
  Module.finrank K (Submodule.span K (L : Set V))

/-- The *scale* `𝔰L`: the `R`-submodule of `K` generated by `B(L, L)`. -/
def scaleIdeal (B : LinearMap.BilinForm K V) (L : Submodule R V) : Submodule R K :=
  Submodule.span R {c | ∃ x ∈ L, ∃ y ∈ L, B x y = c}

/-- The *norm* `𝔫L`: the `R`-submodule of `K` generated by `Q(L) = {B x x : x ∈ L}`. -/
def normIdeal (B : LinearMap.BilinForm K V) (L : Submodule R V) : Submodule R K :=
  Submodule.span R {c | ∃ x ∈ L, B x x = c}

/-- `L` is *integral*: `B(L, L) ⊆ R`. -/
def IsIntegralLattice (B : LinearMap.BilinForm K V) (L : Submodule R V) : Prop :=
  scaleIdeal B L ≤ 1

/-- The *dual lattice* `L^# = {x ∈ K L : B(x, L) ⊆ R}`, computed inside `K L`
(so this is the right notion also for sublattices not on all of `V`). -/
def dual (B : LinearMap.BilinForm K V) (L : Submodule R V) : Submodule R V :=
  LinearMap.BilinForm.dualSubmodule B L ⊓ (Submodule.span K (L : Set V)).restrictScalars R

/-- `L` is *unimodular*: `L^# = L`. For a lattice `L` (finitely generated, `R ≠ K`) this
forces `B` to be nondegenerate on `K L`, and agrees with O'Meara's `𝔳L = R`, `𝔰L = R`. -/
def IsUnimodular (B : LinearMap.BilinForm K V) (L : Submodule R V) : Prop :=
  dual B L = L

end Lattice

end LatticesLean
