name = "lattices-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LatticesLean", "LatticesCounterexamples"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LatticesLean"

[[lean_lib]]
name = "LatticesCounterexamples"
