#!/usr/bin/env python3
"""Generate coverage tables from docstring citations.

Every declaration whose docstring cites a source as `[KEY, locator]` (e.g.
`**[OMeara63, 82:15a]**`, `[Cassels78, Lemma 9.3.1]`, `[HKK78, Theorem 3]`) is listed in
`docs/coverage/generated/KEY.md`, with its Lean name, file and status:

* ✅ proved (no `sorry` in the declaration),
* 📝 stated (the declaration contains `sorry`),
* defined (a definition or structure),
* ↪ alias (a front-door alias in `Papers/`).

Usage (from the repository root):  python3 scripts/coverage.py
Prints a one-line summary per source (used by CI).
"""

import re
from collections import defaultdict
from pathlib import Path

ROOTS = ["LatticesLean", "LatticesCounterexamples"]
OUT = Path("docs/coverage/generated")

DECL = re.compile(
    r"^(?:@\[[^\]]*\]\s*)*(?:private\s+|protected\s+|noncomputable\s+)*"
    r"(theorem|lemma|def|abbrev|structure|class|instance|alias)\s+([^\s:(]+)",
    re.M,
)
DOC = re.compile(r"/--(.*?)-/", re.S)
CITE = re.compile(r"\[([A-Za-z][A-Za-z']*\d*),\s*([^\]]+)\]")


def locator_key(loc: str):
    """Sort locators like 82:15a, Theorem 1.2, Lemma 9.3.1 numerically where possible."""
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", loc)]


def scan(path: Path):
    text = path.read_text(encoding="utf-8")
    decls = list(DECL.finditer(text))
    for i, m in enumerate(decls):
        kind, name = m.group(1), m.group(2)
        # the docstring immediately preceding this declaration (if any)
        before = text[: m.start()].rstrip()
        doc = ""
        if before.endswith("-/"):
            start = before.rfind("/--")
            if start != -1:
                doc = before[start:]
        if not doc:
            continue
        end = decls[i + 1].start() if i + 1 < len(decls) else len(text)
        body = text[m.end():end]
        if kind == "alias":
            status = "↪ alias"
        elif kind in ("def", "abbrev", "structure", "class", "instance"):
            status = "defined"
        elif re.search(r"\bsorry\b", body):
            status = "📝"
        else:
            status = "✅"
        for key, loc in CITE.findall(doc):
            yield key, loc.strip(), name, str(path), status


def main():
    table = defaultdict(list)
    for root in ROOTS:
        for path in sorted(Path(root).rglob("*.lean")):
            for key, loc, name, file, status in scan(path):
                table[key].append((loc, name, file, status))
    OUT.mkdir(parents=True, exist_ok=True)
    for key, rows in sorted(table.items()):
        rows.sort(key=lambda r: (locator_key(r[0]), r[1]))
        lines = [
            f"# Coverage of [{key}]",
            "",
            "Generated by `scripts/coverage.py`; do not edit by hand.",
            "",
            "| Reference | Lean | File | Status |",
            "|---|---|---|---|",
        ]
        lines += [f"| {loc} | `{name}` | `{file}` | {st} |" for loc, name, file, st in rows]
        (OUT / f"{key}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        proved = sum(1 for r in rows if r[3] == "✅")
        stated = sum(1 for r in rows if r[3] == "📝")
        print(f"{key}: {len(rows)} entries, {proved} proved, {stated} stated")


if __name__ == "__main__":
    main()
